### ISSUE TITLE
relay not switching on

### ISSUE THREAD

**Issue by vinodkumar1947** [automote/contiki#1]
Hi manoj,

the relay driver is not switching the PIN DIO3. Voltage remains almost constant at the PIN. Please look into the issue

**Comment by manojsony** [comment]
Hi Vinod ,

We did check the relay code before a day.. and found fine .. You can refer
the examples code : /hello-world.c  where we have tested it .. We verified
the same by o/p displayed by relay driver program on gtkterm .. Lets
discuss more when we meet.

Thanks
Manoj Sony

On Thu, Sep 10, 2015 at 10:36 AM, vinodkumar1947 notifications@github.com
wrote:

> Hi manoj,
> 
> the relay driver is not switching the PIN DIO3. Voltage remains almost
> constant at the PIN. Please look into the issue
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/automote/contiki/issues/1.

## 

## 

Regards,
Manoj Sony,
Mob  : +91-9886 888 101

**Comment by lovelesh** [comment]
@manojsony,

Did you check the voltage on the PIN. The code is working fine but the voltage is hovering from 2.8 to 3.2V

**Comment by manojsony** [comment]
@vinodkumar1947  @lovelesh   : Guys now its been verified and fixed ..please close the bug.

**Comment by lovelesh** [comment]
Thanks @manojsony . I will close this bug.
