### ISSUE TITLE
port coap-relay server to release 3-0

### ISSUE THREAD

**Issue by hknath** [automote/contiki#4]

**Comment by lovelesh** [comment]
@DeshpandeChandana 
please make the code robust so that we can test it on the mote.

**Comment by DeshpandeChandana** [comment]
Server Code is according to the following specifications
1. has GET PUT requests
2. Has a query "color=r/g/b" (could be modified)
3. LED switches ON/OFF on command "mode=on/off"
4. When client ask for status of LED by GET method, server responds with
the current status of LED
5. Upon PUT, depending on the status of LED, switches on/off LED

Let me know if anything else need to be added

**Comment by lovelesh** [comment]
@DeshpandeChandana 
Are the functionality working on the mote? plz confirm which ones are working and which are to be worked on.

Yesterday we checked the methods, can you co-ordinate with @hknath to get better idea of the issue.

**Comment by DeshpandeChandana** [comment]
1. I haven't tested on motes.
2. Completely working on 2.7
3. Working on Contiki 3.0 to make the same
