### ISSUE TITLE
add relay status functionality to relay driver

### ISSUE THREAD

**Issue by hknath** [automote/contiki#5]
@manojsony ,

I want an extra functionality to relay driver to get the status of the relay whether its on or off.
I will use it for displaying status of relay (fan/light) to user.

**Comment by manojsony** [comment]
It will be done by 15 mins once im there at office ... the function will be
relayread(addr,pin)

On Wed, Sep 16, 2015 at 10:56 AM, hknath notifications@github.com wrote:

> Assigned #5 https://github.com/automote/contiki/issues/5 to @manojsony
> https://github.com/manojsony.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/automote/contiki/issues/5#event-410578571.

## 

## 

Regards,
Manoj Sony,
Mob  : +91-9886 888 101

**Comment by manojsony** [comment]
Hemanth ,

Dont mark this as BUG  but mark this as enhancement ... as this was not
asked for us during requirement ... It was reviewed and verified and then
pushed to git

On Wed, Sep 16, 2015 at 12:12 PM, manoj sony manojsony@gmail.com wrote:

> It will be done by 15 mins once im there at office ... the function will
> be relayread(addr,pin)
> 
> On Wed, Sep 16, 2015 at 10:56 AM, hknath notifications@github.com wrote:
> 
> > Assigned #5 https://github.com/automote/contiki/issues/5 to @manojsony
> > https://github.com/manojsony.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/automote/contiki/issues/5#event-410578571.
> 
> ## 
> 
> ## 
> 
> Regards,
> Manoj Sony,
> Mob  : +91-9886 888 101

## 

## 

Regards,
Manoj Sony,
Mob  : +91-9886 888 101

**Comment by hknath** [comment]
If some requirement is missising this is also a bug.

**Comment by lovelesh** [comment]
@manojsony 
please close the bug or request to close if the functionality or bug fix has been done. If this enhancement is complete, I will close the issue.

**Comment by manojsony** [comment]
Completed on 16th Sept 2015 ..
